package command;

public enum CommandType {
    PLAY_COMMAND,
    SEARCH_COMMAND,
    SHOW_PLAYLIST_COMMAND,
    STOP_COMMAND,
    TOP_SONGS_COMMAND,
    ADD_SONG_TO_PLAYLIST_COMMAND,
    CREATE_PLAYLIST_COMMAND,
    DISCONNECT_COMMAND,
    LOGIN_COMMAND,
    REGISTER_COMMAND;
}
